server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
#docker logs
scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)(\-\d|\.\d\.\w+)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_name']
        regex: '^/([\w\-]+)\.?(\d{1,2})?'
        replacement: '$2'
        target_label: 'replica'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'
